package com.persistance.entities;
// Generated 1 janv. 2020 21:50:02 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="client"
    ,catalog="agence1"
)
public class Client  implements java.io.Serializable {


     private int idClient;
     private String nom;
     private String prenom;
     private String adresse;
     private Set<Reservation> reservations = new HashSet<Reservation>(0);

    public Client() {
    }

	
    public Client(int idClient) {
        this.idClient = idClient;
    }
    public Client(int idClient, String nom, String prenom, String adresse, Set<Reservation> reservations) {
       this.idClient = idClient;
       this.nom = nom;
       this.prenom = prenom;
       this.adresse = adresse;
       this.reservations = reservations;
    }
   
     @Id 

    
    @Column(name="idClient", unique=true, nullable=false)
    public int getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(int idClient) {
        this.idClient = idClient;
    }

    
    @Column(name="nom", length=20)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prenom", length=20)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="adresse", length=20)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }




}


