package com.persistance.entities;
// Generated 1 janv. 2020 21:50:02 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hotel generated by hbm2java
 */
@Entity
@Table(name="hotel"
    ,catalog="agence1"
)
public class Hotel  implements java.io.Serializable {


     private int idHotel;
     private String nomHotel;
     private String adresse;
     private Integer tel;
     private Set<Reservation> reservations = new HashSet<Reservation>(0);

    public Hotel() {
    }

	
    public Hotel(int idHotel) {
        this.idHotel = idHotel;
    }
    public Hotel(int idHotel, String nomHotel, String adresse, Integer tel, Set<Reservation> reservations) {
       this.idHotel = idHotel;
       this.nomHotel = nomHotel;
       this.adresse = adresse;
       this.tel = tel;
       this.reservations = reservations;
    }
   
     @Id 

    
    @Column(name="idHotel", unique=true, nullable=false)
    public int getIdHotel() {
        return this.idHotel;
    }
    
    public void setIdHotel(int idHotel) {
        this.idHotel = idHotel;
    }

    
    @Column(name="nomHotel", length=20)
    public String getNomHotel() {
        return this.nomHotel;
    }
    
    public void setNomHotel(String nomHotel) {
        this.nomHotel = nomHotel;
    }

    
    @Column(name="adresse", length=20)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="tel")
    public Integer getTel() {
        return this.tel;
    }
    
    public void setTel(Integer tel) {
        this.tel = tel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hotel")
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }




}


