package com.persistance.entities;
// Generated 1 janv. 2020 21:50:02 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name="reservation"
    ,catalog="agence1"
)
public class Reservation  implements java.io.Serializable {


     private int idReservation;
     private Client client=new Client();
     private Hotel hotel= new Hotel();
     private Date datereservation;
     private Integer nbrenuit;

    public Reservation() {
    }

	
    public Reservation(int idReservation) {
        this.idReservation = idReservation;
    }
    public Reservation(int idReservation, Client client, Hotel hotel, Date datereservation, Integer nbrenuit) {
       this.idReservation = idReservation;
       this.client = client;
       this.hotel = hotel;
       this.datereservation = datereservation;
       this.nbrenuit = nbrenuit;
    }
   
     @Id 

    
    @Column(name="idReservation", unique=true, nullable=false)
    public int getIdReservation() {
        return this.idReservation;
    }
    
    public void setIdReservation(int idReservation) {
        this.idReservation = idReservation;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="idClient")
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="idHotel")
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datereservation", length=0)
    public Date getDatereservation() {
        return this.datereservation;
    }
    
    public void setDatereservation(Date datereservation) {
        this.datereservation = datereservation;
    }

    
    @Column(name="nbrenuit")
    public Integer getNbrenuit() {
        return this.nbrenuit;
    }
    
    public void setNbrenuit(Integer nbrenuit) {
        this.nbrenuit = nbrenuit;
    }




}


